parameters:
#    treewalker_media.example.class: Treewalker\Bundle\MediaBundle\Example

services:
#    treewalker_media.example:
#        class: %treewalker_media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
