parameters:
#    treewalker_blog.example.class: Treewalker\Bundle\BlogBundle\Example

services:
#    treewalker_blog.example:
#        class: %treewalker_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    treewalker_blog.treewalker_blogbundle_price:
       class:  Treewalker\Bundle\BlogBundle\Twig\priceExtension
       tags:
           -  { name: twig.extension }
           
    treewalker_blog.treewalker_blogbundle_file_exists:
        class: Treewalker\Bundle\BlogBundle\Twig\FileExistsExtension
        tags:
            - { name: twig.extension }
            
   
